/*
 *
 * Flowchart constants
 *
 */
export const LOAD_ENTRIES = 'LOAD_ENTRIES';
export const LOADED_ENTRIES = 'LOADED_ENTRIES';
export const ADD_PATHWAY_STEP = 'ADD_PATHWAY_STEP';
export const CLEAR_PATHWAY = 'CLEAR_PATHWAY';
export const TRUNCATE_PATHWAY_TO_STEP = 'TRUNCATE_PATHWAY_TO_STEP';
export const SET_CURRENT_FLOWCHART = 'SET_CURRENT_FLOWCHART';
export const LOADING_ERROR = 'LOADING_ERROR';
export const SET_SHOW_FEEDBACK_MODAL = 'SET_SHOW_FEEDBACK_MODAL';
